# Generated by Django 2.1.4 on 2018-12-28 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel('Import', 'ImportHeader')
    ]
