# Generated by Django 2.1.4 on 2018-12-26 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20181224_1237'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='account_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='account_number',
            new_name='number',
        ),
        migrations.RenameField(
            model_name='bank',
            old_name='bank_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='currency',
            old_name='currency_abbr',
            new_name='abbr',
        ),
        migrations.RenameField(
            model_name='currency',
            old_name='currency_name',
            new_name='name',
        ),
    ]
