# Generated by Django 2.1.4 on 2018-12-27 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20181226_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='hide',
            field=models.BooleanField(default=False),
        ),
    ]
