# Generated by Django 4.1.7 on 2023-02-26 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_account_iban'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='nordigen_id',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
