# Generated by Django 2.1.4 on 2018-12-26 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_auto_20181224_1237'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category_group',
            new_name='group',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='category_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='categorygroup',
            old_name='group_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='transaction_added',
            new_name='added',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='transaction_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='transaction_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='transaction_imported_description',
            new_name='imported_description',
        ),
        migrations.RenameField(
            model_name='transactiontype',
            old_name='type_name',
            new_name='name',
        ),
    ]
