# Generated by Django 2.1.4 on 2018-12-27 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0007_auto_20181227_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='amount_account_currency',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='transaction',
            name='balance_account_currency',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='transaction',
            name='currency_multiplier',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14),
        ),
    ]
