# Generated by Django 2.1.4 on 2018-12-28 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0002_auto_20181228_1213'),
        ('accounts', '0006_bank_hide'),
        ('transactions', '0009_transaction_import_header'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionImportTemp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid_text', models.CharField(blank=True, max_length=200, null=True)),
                ('date', models.DateField()),
                ('added', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('amount_account_currency', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('balance_account_currency', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('currency_multiplier', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('imported_description', models.CharField(blank=True, max_length=2000, null=True)),
                ('type', models.CharField(blank=True, max_length=2000, null=True)),
                ('party_name', models.CharField(blank=True, max_length=500, null=True)),
                ('party_IBAN', models.CharField(blank=True, max_length=200, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.Account')),
                ('import_header', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='toolbox.ImportHeader')),
            ],
        ),
    ]
