# Generated by Django 2.1.4 on 2019-05-25 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0012_transactionimporttemp_is_duplicate'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='approved',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
